version: '3'
services:
    nginx:
    image: mccoc12/nginx
    ports:
      - 80:80
    web:
        build: .
        image: mccoc12/flaskapp
        ports:
           - 5000:5000
        networks:
           - app
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - app
